import { IEmployeeModel } from '../models/user.model';

export const UserListDummy = [
  {
    email: 'admin@example.com',
    password: 'pass@12345',
    firstName: 'Admin',
    lastName: '',
    fullName: 'Admin',
  },
];

export const GroupList = [
  {
    name: 'IT Development',
  },
  {
    name: 'IT Infrastructure',
  },
  {
    name: 'IT Suuport',
  },
  {
    name: 'Marketing',
  },
  {
    name: 'Finance',
  },
  {
    name: 'Human Resource',
  },
  {
    name: 'Customer Service',
  },
  {
    name: 'Accounting',
  },
  {
    name: 'Engineering',
  },
  {
    name: 'Sales',
  },
];

export const EmployeeListDummy: IEmployeeModel[] = [
  {
    id: 'E02002',
    firstName: 'Kai',
    lastName: 'Le',
    basicSalary: 9236800,
    birthDate: '2010/4/16',
    description: '',
    email: 'kai.le@example.com',
    group: 'Accounting',
    status: 'Tetap',
    userName: 'kai.le',
  },
  {
    id: 'E02003',
    firstName: 'Robert',
    lastName: 'Patel',
    basicSalary: 4570300,
    birthDate: '2017/2/9',
    description: '',
    email: 'robert.patel@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'robert.patel',
  },
  {
    id: 'E02004',
    firstName: 'Cameron',
    lastName: 'Lo',
    basicSalary: 8357600,
    birthDate: '2014/4/20',
    description: '',
    email: 'cameron.lo@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'cameron.lo',
  },
  {
    id: 'E02005',
    firstName: 'Harper',
    lastName: 'Castillo',
    basicSalary: 9806200,
    birthDate: '2019/3/23',
    description: '',
    email: 'harper.castillo@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'harper.castillo',
  },
  {
    id: 'E02006',
    firstName: 'Harper',
    lastName: 'Dominguez',
    basicSalary: 17539100,
    birthDate: '2013/3/12',
    description: '',
    email: 'harper.dominguez@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'harper.dominguez',
  },
  {
    id: 'E02007',
    firstName: 'Ezra',
    lastName: 'Vu',
    basicSalary: 6622700,
    birthDate: '2016/3/3',
    description: '',
    email: 'ezra.vu@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'ezra.vu',
  },
  {
    id: 'E02008',
    firstName: 'Jade',
    lastName: 'Hu',
    basicSalary: 8974400,
    birthDate: '2013/6/20',
    description: '',
    email: 'jade.hu@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'jade.hu',
  },
  {
    id: 'E02009',
    firstName: 'Miles',
    lastName: 'Chang',
    basicSalary: 6967400,
    birthDate: '2013/9/25',
    description: '',
    email: 'miles.chang@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'miles.chang',
  },
  {
    id: 'E02010',
    firstName: 'Gianna',
    lastName: 'Holmes',
    basicSalary: 9763000,
    birthDate: '2014/9/11',
    description: '',
    email: 'gianna.holmes@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'gianna.holmes',
  },
  {
    id: 'E02011',
    firstName: 'Jameson',
    lastName: 'Thomas',
    basicSalary: 10587900,
    birthDate: '2017/7/18',
    description: '',
    email: 'jameson.thomas@example.com',
    group: 'Engineering',
    status: 'Tetap',
    userName: 'jameson.thomas',
  },
  {
    id: 'E02012',
    firstName: 'Jameson',
    lastName: 'Pena',
    basicSalary: 4049900,
    birthDate: '2015/5/22',
    description: '',
    email: 'jameson.pena@example.com',
    group: 'Accounting',
    status: 'Magang',
    userName: 'jameson.pena',
  },
  {
    id: 'E02013',
    firstName: 'Bella',
    lastName: 'Wu',
    basicSalary: 7141800,
    birthDate: '2013/9/1',
    description: '',
    email: 'bella.wu@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'bella.wu',
  },
  {
    id: 'E02014',
    firstName: 'Jose',
    lastName: 'Wong',
    basicSalary: 15055800,
    birthDate: '2020/4/7',
    description: '',
    email: 'jose.wong@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'jose.wong',
  },
  {
    id: 'E02015',
    firstName: 'Lucas',
    lastName: 'Richardson',
    basicSalary: 11891200,
    birthDate: '2011/7/3',
    description: '',
    email: 'lucas.richardson@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'lucas.richardson',
  },
  {
    id: 'E02016',
    firstName: 'Jacob',
    lastName: 'Moore',
    basicSalary: 13142200,
    birthDate: '2019/10/22',
    description: '',
    email: 'jacob.moore@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'jacob.moore',
  },
  {
    id: 'E02017',
    firstName: 'Luna',
    lastName: 'Lu',
    basicSalary: 6420800,
    birthDate: '2019/10/24',
    description: '',
    email: 'luna.lu@example.com',
    group: 'Finance',
    status: 'Magang',
    userName: 'luna.lu',
  },
  {
    id: 'E02018',
    firstName: 'Bella',
    lastName: 'Tran',
    basicSalary: 25448600,
    birthDate: '2014/6/17',
    description: '',
    email: 'bella.tran@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'bella.tran',
  },
  {
    id: 'E02019',
    firstName: 'Ivy',
    lastName: 'Chau',
    basicSalary: 5481100,
    birthDate: '2020/9/14',
    description: '',
    email: 'ivy.chau@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'ivy.chau',
  },
  {
    id: 'E02020',
    firstName: 'Jordan',
    lastName: 'Kumar',
    basicSalary: 9572900,
    birthDate: '2010/5/4',
    description: '',
    email: 'jordan.kumar@example.com',
    group: 'IT Suuport',
    status: 'Kontrak',
    userName: 'jordan.kumar',
  },
  {
    id: 'E02021',
    firstName: 'Sophia',
    lastName: 'Gutierrez',
    basicSalary: 10264900,
    birthDate: '2010/8/19',
    description: '',
    email: 'sophia.gutierrez@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'sophia.gutierrez',
  },
  {
    id: 'E02022',
    firstName: 'Eli',
    lastName: 'Dang',
    basicSalary: 12287500,
    birthDate: '2010/1/25',
    description: '',
    email: 'eli.dang@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'eli.dang',
  },
  {
    id: 'E02023',
    firstName: 'Lillian',
    lastName: 'Lewis',
    basicSalary: 8332300,
    birthDate: '2020/7/5',
    description: '',
    email: 'lillian.lewis@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'lillian.lewis',
  },
  {
    id: 'E02024',
    firstName: 'Serenity',
    lastName: 'Cao',
    basicSalary: 6672100,
    birthDate: '2010/1/14',
    description: '',
    email: 'serenity.cao@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'serenity.cao',
  },
  {
    id: 'E02025',
    firstName: 'Parker',
    lastName: 'Lai',
    basicSalary: 24640000,
    birthDate: '2019/10/9',
    description: '',
    email: 'parker.lai@example.com',
    group: 'IT Suuport',
    status: 'Kontrak',
    userName: 'parker.lai',
  },
  {
    id: 'E02026',
    firstName: 'Charles',
    lastName: 'Simmons',
    basicSalary: 11352500,
    birthDate: '2018/5/2',
    description: '',
    email: 'charles.simmons@example.com',
    group: 'Accounting',
    status: 'Kontrak',
    userName: 'charles.simmons',
  },
  {
    id: 'E02027',
    firstName: 'Jayden',
    lastName: 'Luu',
    basicSalary: 18434200,
    birthDate: '2013/8/19',
    description: '',
    email: 'jayden.luu@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'jayden.luu',
  },
  {
    id: 'E02028',
    firstName: 'Brooks',
    lastName: 'Richardson',
    basicSalary: 15134100,
    birthDate: '2019/3/24',
    description: '',
    email: 'brooks.richardson@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'brooks.richardson',
  },
  {
    id: 'E02029',
    firstName: 'Ivy',
    lastName: 'Thompson',
    basicSalary: 11890000,
    birthDate: '2017/10/13',
    description: '',
    email: 'ivy.thompson@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'ivy.thompson',
  },
  {
    id: 'E02030',
    firstName: 'Peyton',
    lastName: 'Wright',
    basicSalary: 15337000,
    birthDate: '2015/10/18',
    description: '',
    email: 'peyton.wright@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'peyton.wright',
  },
  {
    id: 'E02031',
    firstName: 'Wyatt',
    lastName: 'Dinh',
    basicSalary: 7286000,
    birthDate: '2015/3/1',
    description: '',
    email: 'wyatt.dinh@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'wyatt.dinh',
  },
  {
    id: 'E02032',
    firstName: 'Ruby',
    lastName: 'Alexander',
    basicSalary: 25561000,
    birthDate: '2017/8/21',
    description: '',
    email: 'ruby.alexander@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'ruby.alexander',
  },
  {
    id: 'E02033',
    firstName: 'Axel',
    lastName: 'Oh',
    basicSalary: 8496200,
    birthDate: '2013/5/5',
    description: '',
    email: 'axel.oh@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'axel.oh',
  },
  {
    id: 'E02034',
    firstName: 'Axel',
    lastName: 'Ramirez',
    basicSalary: 10379500,
    birthDate: '2012/5/11',
    description: '',
    email: 'axel.ramirez@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'axel.ramirez',
  },
  {
    id: 'E02035',
    firstName: 'Liliana',
    lastName: 'Chang',
    basicSalary: 9750900,
    birthDate: '2020/6/15',
    description: '',
    email: 'liliana.chang@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'liliana.chang',
  },
  {
    id: 'E02036',
    firstName: 'Leonardo',
    lastName: 'Carter',
    basicSalary: 5493100,
    birthDate: '2017/8/5',
    description: '',
    email: 'leonardo.carter@example.com',
    group: 'Finance',
    status: 'Magang',
    userName: 'leonardo.carter',
  },
  {
    id: 'E02037',
    firstName: 'Landon',
    lastName: 'Gonzales',
    basicSalary: 8868900,
    birthDate: '2010/10/18',
    description: '',
    email: 'landon.gonzales@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'landon.gonzales',
  },
  {
    id: 'E02038',
    firstName: 'Amelia',
    lastName: 'Dominguez',
    basicSalary: 15818400,
    birthDate: '2018/6/14',
    description: '',
    email: 'amelia.dominguez@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'amelia.dominguez',
  },
  {
    id: 'E02039',
    firstName: 'Silas',
    lastName: 'Ross',
    basicSalary: 4852300,
    birthDate: '2016/4/22',
    description: '',
    email: 'silas.ross@example.com',
    group: 'Human Resource',
    status: 'Magang',
    userName: 'silas.ross',
  },
  {
    id: 'E02040',
    firstName: 'Jeremiah',
    lastName: 'Cheng',
    basicSalary: 7094600,
    birthDate: '2020/4/24',
    description: '',
    email: 'jeremiah.cheng@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'jeremiah.cheng',
  },
  {
    id: 'E02041',
    firstName: 'Chloe',
    lastName: 'Chin',
    basicSalary: 13448700,
    birthDate: '2015/6/8',
    description: '',
    email: 'chloe.chin@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'chloe.chin',
  },
  {
    id: 'E02042',
    firstName: 'Ella',
    lastName: 'Martinez',
    basicSalary: 7611100,
    birthDate: '2018/10/19',
    description: '',
    email: 'ella.martinez@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'ella.martinez',
  },
  {
    id: 'E02043',
    firstName: 'Gianna',
    lastName: 'Jones',
    basicSalary: 11922000,
    birthDate: '2010/9/10',
    description: '',
    email: 'gianna.jones@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'gianna.jones',
  },
  {
    id: 'E02044',
    firstName: 'Austin',
    lastName: 'Chow',
    basicSalary: 18085800,
    birthDate: '2015/8/2',
    description: '',
    email: 'austin.chow@example.com',
    group: 'Accounting',
    status: 'Tetap',
    userName: 'austin.chow',
  },
  {
    id: 'E02045',
    firstName: 'Ella',
    lastName: 'Chen',
    basicSalary: 11407200,
    birthDate: '2017/2/15',
    description: '',
    email: 'ella.chen@example.com',
    group: 'IT Suuport',
    status: 'Tetap',
    userName: 'ella.chen',
  },
  {
    id: 'E02046',
    firstName: 'Ruby',
    lastName: 'Kaur',
    basicSalary: 9167200,
    birthDate: '2010/6/25',
    description: '',
    email: 'ruby.kaur@example.com',
    group: 'Accounting',
    status: 'Magang',
    userName: 'ruby.kaur',
  },
  {
    id: 'E02047',
    firstName: 'Savannah',
    lastName: 'Morales',
    basicSalary: 7154200,
    birthDate: '2013/5/11',
    description: '',
    email: 'savannah.morales@example.com',
    group: 'Accounting',
    status: 'Kontrak',
    userName: 'savannah.morales',
  },
  {
    id: 'E02048',
    firstName: 'Luca',
    lastName: 'Powell',
    basicSalary: 5470000,
    birthDate: '2017/3/16',
    description: '',
    email: 'luca.powell@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'luca.powell',
  },
  {
    id: 'E02049',
    firstName: 'Parker',
    lastName: 'Thao',
    basicSalary: 6502200,
    birthDate: '2014/7/13',
    description: '',
    email: 'parker.thao@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'parker.thao',
  },
  {
    id: 'E02050',
    firstName: 'Ryan',
    lastName: 'Vo',
    basicSalary: 6510900,
    birthDate: '2011/8/15',
    description: '',
    email: 'ryan.vo@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'ryan.vo',
  },
  {
    id: 'E02051',
    firstName: 'Isabella',
    lastName: 'Ngo',
    basicSalary: 12659800,
    birthDate: '2019/1/5',
    description: '',
    email: 'isabella.ngo@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'isabella.ngo',
  },
  {
    id: 'E02052',
    firstName: 'Leah',
    lastName: 'Vega',
    basicSalary: 7238800,
    birthDate: '2014/7/18',
    description: '',
    email: 'leah.vega@example.com',
    group: 'Finance',
    status: 'Magang',
    userName: 'leah.vega',
  },
  {
    id: 'E02053',
    firstName: 'Jaxson',
    lastName: 'Liu',
    basicSalary: 20521600,
    birthDate: '2015/5/19',
    description: '',
    email: 'jaxson.liu@example.com',
    group: 'Human Resource',
    status: 'Magang',
    userName: 'jaxson.liu',
  },
  {
    id: 'E02054',
    firstName: 'Santiago',
    lastName: 'f',
    basicSalary: 7400400,
    birthDate: '2013/8/7',
    description: '',
    email: 'santiago.f@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'santiago.f',
  },
  {
    id: 'E02055',
    firstName: 'Layla',
    lastName: 'Bell',
    basicSalary: 20303000,
    birthDate: '2019/5/20',
    description: '',
    email: 'layla.bell@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'layla.bell',
  },
  {
    id: 'E02056',
    firstName: 'Bella',
    lastName: 'Morales',
    basicSalary: 19486400,
    birthDate: '2016/10/10',
    description: '',
    email: 'bella.morales@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'bella.morales',
  },
  {
    id: 'E02057',
    firstName: 'Eliza',
    lastName: 'Kang',
    basicSalary: 7665900,
    birthDate: '2014/10/5',
    description: '',
    email: 'eliza.kang@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'eliza.kang',
  },
  {
    id: 'E02058',
    firstName: 'Gabriel',
    lastName: 'Reyes',
    basicSalary: 10163000,
    birthDate: '2018/7/8',
    description: '',
    email: 'gabriel.reyes@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'gabriel.reyes',
  },
  {
    id: 'E02059',
    firstName: 'Piper',
    lastName: 'Garcia',
    basicSalary: 12692900,
    birthDate: '2016/8/2',
    description: '',
    email: 'piper.garcia@example.com',
    group: 'Engineering',
    status: 'Tetap',
    userName: 'piper.garcia',
  },
  {
    id: 'E02060',
    firstName: 'Jacob',
    lastName: 'Cheng',
    basicSalary: 15589000,
    birthDate: '2011/9/12',
    description: '',
    email: 'jacob.cheng@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'jacob.cheng',
  },
  {
    id: 'E02061',
    firstName: 'Nathan',
    lastName: 'Hong',
    basicSalary: 15063100,
    birthDate: '2015/4/16',
    description: '',
    email: 'nathan.hong@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'nathan.hong',
  },
  {
    id: 'E02062',
    firstName: 'Chloe',
    lastName: 'Kim',
    basicSalary: 7285000,
    birthDate: '2016/10/7',
    description: '',
    email: 'chloe.kim@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'chloe.kim',
  },
  {
    id: 'E02063',
    firstName: 'Isaac',
    lastName: 'Guzman',
    basicSalary: 5795100,
    birthDate: '2013/8/22',
    description: '',
    email: 'isaac.guzman@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'isaac.guzman',
  },
  {
    id: 'E02064',
    firstName: 'Julian',
    lastName: 'Ford',
    basicSalary: 7034000,
    birthDate: '2012/3/13',
    description: '',
    email: 'julian.ford@example.com',
    group: 'Finance',
    status: 'Magang',
    userName: 'julian.ford',
  },
  {
    id: 'E02065',
    firstName: 'Kinsley',
    lastName: 'Liang',
    basicSalary: 9822100,
    birthDate: '2020/3/19',
    description: '',
    email: 'kinsley.liang@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'kinsley.liang',
  },
  {
    id: 'E02066',
    firstName: 'Wesley',
    lastName: 'Yu',
    basicSalary: 12717500,
    birthDate: '2016/6/20',
    description: '',
    email: 'wesley.yu@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'wesley.yu',
  },
  {
    id: 'E02067',
    firstName: 'Serenity',
    lastName: 'Martin',
    basicSalary: 9754200,
    birthDate: '2016/1/10',
    description: '',
    email: 'serenity.martin@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'serenity.martin',
  },
  {
    id: 'E02068',
    firstName: 'Ethan',
    lastName: 'Sanchez',
    basicSalary: 8164600,
    birthDate: '2018/6/8',
    description: '',
    email: 'ethan.sanchez@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'ethan.sanchez',
  },
  {
    id: 'E02069',
    firstName: 'David',
    lastName: 'Sanchez',
    basicSalary: 18205500,
    birthDate: '2018/7/20',
    description: '',
    email: 'david.sanchez@example.com',
    group: 'Engineering',
    status: 'Tetap',
    userName: 'david.sanchez',
  },
  {
    id: 'E02070',
    firstName: 'Elias',
    lastName: 'Hsu',
    basicSalary: 8677700,
    birthDate: '2019/4/5',
    description: '',
    email: 'elias.hsu@example.com',
    group: 'Accounting',
    status: 'Kontrak',
    userName: 'elias.hsu',
  },
  {
    id: 'E02071',
    firstName: 'Luca',
    lastName: 'Phan',
    basicSalary: 12994900,
    birthDate: '2011/2/8',
    description: '',
    email: 'luca.phan@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'luca.phan',
  },
  {
    id: 'E02072',
    firstName: 'Olivia',
    lastName: 'Xi',
    basicSalary: 12453500,
    birthDate: '2011/2/20',
    description: '',
    email: 'olivia.xi@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'olivia.xi',
  },
  {
    id: 'E02073',
    firstName: 'Alice',
    lastName: 'Luu',
    basicSalary: 8108300,
    birthDate: '2012/6/22',
    description: '',
    email: 'alice.luu@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'alice.luu',
  },
  {
    id: 'E02074',
    firstName: 'Leonardo',
    lastName: 'Ng',
    basicSalary: 5772700,
    birthDate: '2014/2/20',
    description: '',
    email: 'leonardo.ng@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'leonardo.ng',
  },
  {
    id: 'E02075',
    firstName: 'Peyton',
    lastName: 'Edwards',
    basicSalary: 5934400,
    birthDate: '2017/10/10',
    description: '',
    email: 'peyton.edwards@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'peyton.edwards',
  },
  {
    id: 'E02076',
    firstName: 'Axel',
    lastName: 'Patel',
    basicSalary: 7320300,
    birthDate: '2016/3/2',
    description: '',
    email: 'axel.patel@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'axel.patel',
  },
  {
    id: 'E02077',
    firstName: 'Eva',
    lastName: 'Chavez',
    basicSalary: 8307000,
    birthDate: '2013/2/2',
    description: '',
    email: 'eva.chavez@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'eva.chavez',
  },
  {
    id: 'E02078',
    firstName: 'Savannah',
    lastName: 'Lee',
    basicSalary: 10400800,
    birthDate: '2020/9/10',
    description: '',
    email: 'savannah.lee@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'savannah.lee',
  },
  {
    id: 'E02079',
    firstName: 'Mia',
    lastName: 'Grant',
    basicSalary: 7092300,
    birthDate: '2014/1/14',
    description: '',
    email: 'mia.grant@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'mia.grant',
  },
  {
    id: 'E02080',
    firstName: 'Eli',
    lastName: 'Richardson',
    basicSalary: 15912100,
    birthDate: '2017/4/5',
    description: '',
    email: 'eli.richardson@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'eli.richardson',
  },
  {
    id: 'E02081',
    firstName: 'Eloise',
    lastName: 'Perry',
    basicSalary: 8892100,
    birthDate: '2013/9/16',
    description: '',
    email: 'eloise.perry@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'eloise.perry',
  },
  {
    id: 'E02082',
    firstName: 'Ian',
    lastName: 'Cheng',
    basicSalary: 12670400,
    birthDate: '2017/9/6',
    description: '',
    email: 'ian.cheng@example.com',
    group: 'Accounting',
    status: 'Magang',
    userName: 'ian.cheng',
  },
  {
    id: 'E02083',
    firstName: 'Penelope',
    lastName: 'Chan',
    basicSalary: 5770400,
    birthDate: '2014/9/2',
    description: '',
    email: 'penelope.chan@example.com',
    group: 'Accounting',
    status: 'Magang',
    userName: 'penelope.chan',
  },
  {
    id: 'E02084',
    firstName: 'Sofia',
    lastName: 'Vasquez',
    basicSalary: 19145500,
    birthDate: '2020/5/8',
    description: '',
    email: 'sofia.vasquez@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'sofia.vasquez',
  },
  {
    id: 'E02085',
    firstName: 'Anthony',
    lastName: 'Baker',
    basicSalary: 9993700,
    birthDate: '2017/2/22',
    description: '',
    email: 'anthony.baker@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'anthony.baker',
  },
  {
    id: 'E02086',
    firstName: 'Lucas',
    lastName: 'Luong',
    basicSalary: 4077800,
    birthDate: '2019/5/1',
    description: '',
    email: 'lucas.luong@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'lucas.luong',
  },
  {
    id: 'E02087',
    firstName: 'Xavier',
    lastName: 'Patel',
    basicSalary: 18774000,
    birthDate: '2017/6/16',
    description: '',
    email: 'xavier.patel@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'xavier.patel',
  },
  {
    id: 'E02088',
    firstName: 'Robert',
    lastName: 'Soto',
    basicSalary: 7238400,
    birthDate: '2010/7/13',
    description: '',
    email: 'robert.soto@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'robert.soto',
  },
  {
    id: 'E02089',
    firstName: 'Nevaeh',
    lastName: 'Jiang',
    basicSalary: 14331800,
    birthDate: '2010/5/19',
    description: '',
    email: 'nevaeh.jiang@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'nevaeh.jiang',
  },
  {
    id: 'E02090',
    firstName: 'Chloe',
    lastName: 'Reyes',
    basicSalary: 19130400,
    birthDate: '2020/8/13',
    description: '',
    email: 'chloe.reyes@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'chloe.reyes',
  },
  {
    id: 'E02091',
    firstName: 'Lucy',
    lastName: 'Edwards',
    basicSalary: 17587500,
    birthDate: '2013/6/6',
    description: '',
    email: 'lucy.edwards@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'lucy.edwards',
  },
  {
    id: 'E02092',
    firstName: 'Luna',
    lastName: 'Edwards',
    basicSalary: 10672600,
    birthDate: '2020/2/16',
    description: '',
    email: 'luna.edwards@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'luna.edwards',
  },
  {
    id: 'E02093',
    firstName: 'Stella',
    lastName: 'Daniels',
    basicSalary: 7263700,
    birthDate: '2017/1/14',
    description: '',
    email: 'stella.daniels@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'stella.daniels',
  },
  {
    id: 'E02094',
    firstName: 'Ayla',
    lastName: 'Ma',
    basicSalary: 11830400,
    birthDate: '2020/4/16',
    description: '',
    email: 'ayla.ma@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'ayla.ma',
  },
  {
    id: 'E02095',
    firstName: 'Matthew',
    lastName: 'Avila',
    basicSalary: 6859200,
    birthDate: '2019/6/5',
    description: '',
    email: 'matthew.avila@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'matthew.avila',
  },
  {
    id: 'E02096',
    firstName: 'Gianna',
    lastName: 'Lim',
    basicSalary: 4253200,
    birthDate: '2015/10/4',
    description: '',
    email: 'gianna.lim@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'gianna.lim',
  },
  {
    id: 'E02097',
    firstName: 'Joseph',
    lastName: 'Tan',
    basicSalary: 6507300,
    birthDate: '2016/6/2',
    description: '',
    email: 'joseph.tan@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'joseph.tan',
  },
  {
    id: 'E02098',
    firstName: 'Connor',
    lastName: 'Lai',
    basicSalary: 11103500,
    birthDate: '2018/1/20',
    description: '',
    email: 'connor.lai@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'connor.lai',
  },
  {
    id: 'E02099',
    firstName: 'Ava',
    lastName: 'Owens',
    basicSalary: 6306600,
    birthDate: '2019/8/13',
    description: '',
    email: 'ava.owens@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'ava.owens',
  },
  {
    id: 'E02100',
    firstName: 'Dylan',
    lastName: 'Aguilar',
    basicSalary: 18619200,
    birthDate: '2016/5/19',
    description: '',
    email: 'dylan.aguilar@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'dylan.aguilar',
  },
  {
    id: 'E02101',
    firstName: 'Leah',
    lastName: 'Zheng',
    basicSalary: 18293800,
    birthDate: '2019/2/23',
    description: '',
    email: 'leah.zheng@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'leah.zheng',
  },
  {
    id: 'E02102',
    firstName: 'Jade',
    lastName: 'Pham',
    basicSalary: 5393100,
    birthDate: '2012/3/9',
    description: '',
    email: 'jade.pham@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'jade.pham',
  },
  {
    id: 'E02103',
    firstName: 'Theodore',
    lastName: 'Bui',
    basicSalary: 25214000,
    birthDate: '2010/2/22',
    description: '',
    email: 'theodore.bui@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'theodore.bui',
  },
  {
    id: 'E02104',
    firstName: 'Asher',
    lastName: 'Chan',
    basicSalary: 7304100,
    birthDate: '2012/5/24',
    description: '',
    email: 'asher.chan@example.com',
    group: 'Accounting',
    status: 'Kontrak',
    userName: 'asher.chan',
  },
  {
    id: 'E02105',
    firstName: 'Ezekiel',
    lastName: 'Brown',
    basicSalary: 12031500,
    birthDate: '2011/6/21',
    description: '',
    email: 'ezekiel.brown@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'ezekiel.brown',
  },
  {
    id: 'E02106',
    firstName: 'Peyton',
    lastName: 'Allen',
    basicSalary: 11226400,
    birthDate: '2014/9/10',
    description: '',
    email: 'peyton.allen@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'peyton.allen',
  },
  {
    id: 'E02107',
    firstName: 'Parker',
    lastName: 'Joseph',
    basicSalary: 5503900,
    birthDate: '2017/3/20',
    description: '',
    email: 'parker.joseph@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'parker.joseph',
  },
  {
    id: 'E02108',
    firstName: 'Kayden',
    lastName: 'Ortiz',
    basicSalary: 13478200,
    birthDate: '2010/4/3',
    description: '',
    email: 'kayden.ortiz@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'kayden.ortiz',
  },
  {
    id: 'E02109',
    firstName: 'Lillian',
    lastName: 'Desai',
    basicSalary: 9280600,
    birthDate: '2010/7/23',
    description: '',
    email: 'lillian.desai@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'lillian.desai',
  },
  {
    id: 'E02110',
    firstName: 'Avery',
    lastName: 'Gutierrez',
    basicSalary: 18102800,
    birthDate: '2011/6/5',
    description: '',
    email: 'avery.gutierrez@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'avery.gutierrez',
  },
  {
    id: 'E02111',
    firstName: 'Caroline',
    lastName: 'Sandoval',
    basicSalary: 4811700,
    birthDate: '2013/9/12',
    description: '',
    email: 'caroline.sandoval@example.com',
    group: 'Accounting',
    status: 'Magang',
    userName: 'caroline.sandoval',
  },
  {
    id: 'E02112',
    firstName: 'Hailey',
    lastName: 'Lim',
    basicSalary: 19275300,
    birthDate: '2018/7/9',
    description: '',
    email: 'hailey.lim@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'hailey.lim',
  },
  {
    id: 'E02113',
    firstName: 'Roman',
    lastName: 'Liang',
    basicSalary: 8520600,
    birthDate: '2010/4/12',
    description: '',
    email: 'roman.liang@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'roman.liang',
  },
  {
    id: 'E02114',
    firstName: 'Elias',
    lastName: 'Rojas',
    basicSalary: 5829000,
    birthDate: '2019/2/7',
    description: '',
    email: 'elias.rojas@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'elias.rojas',
  },
  {
    id: 'E02115',
    firstName: 'Quinn',
    lastName: 'Lai',
    basicSalary: 4194600,
    birthDate: '2020/9/4',
    description: '',
    email: 'quinn.lai@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'quinn.lai',
  },
  {
    id: 'E02116',
    firstName: 'Clara',
    lastName: 'Le',
    basicSalary: 7938800,
    birthDate: '2011/6/19',
    description: '',
    email: 'clara.le@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'clara.le',
  },
  {
    id: 'E02117',
    firstName: 'Chloe',
    lastName: 'Yoon',
    basicSalary: 8385400,
    birthDate: '2013/8/14',
    description: '',
    email: 'chloe.yoon@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'chloe.yoon',
  },
  {
    id: 'E02118',
    firstName: 'Abigail',
    lastName: 'Simmons',
    basicSalary: 12655000,
    birthDate: '2017/6/1',
    description: '',
    email: 'abigail.simmons@example.com',
    group: 'Engineering',
    status: 'Tetap',
    userName: 'abigail.simmons',
  },
  {
    id: 'E02119',
    firstName: 'Ayla',
    lastName: 'Espinoza',
    basicSalary: 19970500,
    birthDate: '2010/5/9',
    description: '',
    email: 'ayla.espinoza@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'ayla.espinoza',
  },
  {
    id: 'E02120',
    firstName: 'Nova',
    lastName: 'Lin',
    basicSalary: 20123500,
    birthDate: '2019/10/6',
    description: '',
    email: 'nova.lin@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'nova.lin',
  },
  {
    id: 'E02121',
    firstName: 'Sadie',
    lastName: 'Singh',
    basicSalary: 18271700,
    birthDate: '2019/1/13',
    description: '',
    email: 'sadie.singh@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'sadie.singh',
  },
  {
    id: 'E02122',
    firstName: 'Aaron',
    lastName: 'Powell',
    basicSalary: 7997500,
    birthDate: '2010/1/8',
    description: '',
    email: 'aaron.powell@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'aaron.powell',
  },
  {
    id: 'E02123',
    firstName: 'Jameson',
    lastName: 'Vargas',
    basicSalary: 19655400,
    birthDate: '2020/9/3',
    description: '',
    email: 'jameson.vargas@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'jameson.vargas',
  },
  {
    id: 'E02124',
    firstName: 'Logan',
    lastName: 'Young',
    basicSalary: 23939500,
    birthDate: '2011/8/24',
    description: '',
    email: 'logan.young@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'logan.young',
  },
  {
    id: 'E02125',
    firstName: 'Wyatt',
    lastName: 'Cheung',
    basicSalary: 5370300,
    birthDate: '2017/10/14',
    description: '',
    email: 'wyatt.cheung@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'wyatt.cheung',
  },
  {
    id: 'E02126',
    firstName: 'Lucas',
    lastName: 'Zhu',
    basicSalary: 12348000,
    birthDate: '2020/5/12',
    description: '',
    email: 'lucas.zhu@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'lucas.zhu',
  },
  {
    id: 'E02127',
    firstName: 'Emily',
    lastName: 'Hong',
    basicSalary: 4119700,
    birthDate: '2018/6/1',
    description: '',
    email: 'emily.hong@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'emily.hong',
  },
  {
    id: 'E02128',
    firstName: 'Luke',
    lastName: 'Ramos',
    basicSalary: 7246300,
    birthDate: '2020/8/16',
    description: '',
    email: 'luke.ramos@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'luke.ramos',
  },
  {
    id: 'E02129',
    firstName: 'Maya',
    lastName: 'Gupta',
    basicSalary: 8767500,
    birthDate: '2011/8/11',
    description: '',
    email: 'maya.gupta@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'maya.gupta',
  },
  {
    id: 'E02130',
    firstName: 'Eliana',
    lastName: 'Ha',
    basicSalary: 5583300,
    birthDate: '2018/5/9',
    description: '',
    email: 'eliana.ha@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'eliana.ha',
  },
  {
    id: 'E02131',
    firstName: 'Lillian',
    lastName: 'Cheng',
    basicSalary: 5820800,
    birthDate: '2017/6/17',
    description: '',
    email: 'lillian.cheng@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'lillian.cheng',
  },
  {
    id: 'E02132',
    firstName: 'Alexander',
    lastName: 'Pena',
    basicSalary: 7563300,
    birthDate: '2017/2/17',
    description: '',
    email: 'alexander.pena@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'alexander.pena',
  },
  {
    id: 'E02133',
    firstName: 'Leonardo',
    lastName: 'Mai',
    basicSalary: 7909000,
    birthDate: '2013/8/23',
    description: '',
    email: 'leonardo.mai@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'leonardo.mai',
  },
  {
    id: 'E02134',
    firstName: 'Jack',
    lastName: 'Phillips',
    basicSalary: 6613800,
    birthDate: '2012/8/3',
    description: '',
    email: 'jack.phillips@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'jack.phillips',
  },
  {
    id: 'E02135',
    firstName: 'Scarlett',
    lastName: 'Delgado',
    basicSalary: 8072800,
    birthDate: '2012/2/23',
    description: '',
    email: 'scarlett.delgado@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'scarlett.delgado',
  },
  {
    id: 'E02136',
    firstName: 'Jack',
    lastName: 'Rogers',
    basicSalary: 4620200,
    birthDate: '2016/5/6',
    description: '',
    email: 'jack.rogers@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'jack.rogers',
  },
  {
    id: 'E02137',
    firstName: 'Violet',
    lastName: 'Huynh',
    basicSalary: 12309600,
    birthDate: '2020/6/22',
    description: '',
    email: 'violet.huynh@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'violet.huynh',
  },
  {
    id: 'E02138',
    firstName: 'Victoria',
    lastName: 'Park',
    basicSalary: 4598900,
    birthDate: '2010/3/7',
    description: '',
    email: 'victoria.park@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'victoria.park',
  },
  {
    id: 'E02139',
    firstName: 'Elizabeth',
    lastName: 'Rodriguez',
    basicSalary: 14075600,
    birthDate: '2012/9/2',
    description: '',
    email: 'elizabeth.rodriguez@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'elizabeth.rodriguez',
  },
  {
    id: 'E02140',
    firstName: 'Samuel',
    lastName: 'Kumar',
    basicSalary: 8526100,
    birthDate: '2010/1/5',
    description: '',
    email: 'samuel.kumar@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'samuel.kumar',
  },
  {
    id: 'E02141',
    firstName: 'Zoe',
    lastName: 'Maldonado',
    basicSalary: 19822200,
    birthDate: '2017/1/1',
    description: '',
    email: 'zoe.maldonado@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'zoe.maldonado',
  },
  {
    id: 'E02142',
    firstName: 'Natalia',
    lastName: 'Richardson',
    basicSalary: 15082500,
    birthDate: '2016/9/24',
    description: '',
    email: 'natalia.richardson@example.com',
    group: 'Engineering',
    status: 'Magang',
    userName: 'natalia.richardson',
  },
  {
    id: 'E02143',
    firstName: 'Madeline',
    lastName: 'Contreras',
    basicSalary: 5931100,
    birthDate: '2011/10/2',
    description: '',
    email: 'madeline.contreras@example.com',
    group: 'Accounting',
    status: 'Tetap',
    userName: 'madeline.contreras',
  },
  {
    id: 'E02144',
    firstName: 'Raelynn',
    lastName: 'Espinoza',
    basicSalary: 4441100,
    birthDate: '2018/4/20',
    description: '',
    email: 'raelynn.espinoza@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'raelynn.espinoza',
  },
  {
    id: 'E02145',
    firstName: 'Noah',
    lastName: 'Rojas',
    basicSalary: 6940800,
    birthDate: '2013/4/9',
    description: '',
    email: 'noah.rojas@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'noah.rojas',
  },
  {
    id: 'E02146',
    firstName: 'Jack',
    lastName: 'Ramos',
    basicSalary: 9675900,
    birthDate: '2018/10/2',
    description: '',
    email: 'jack.ramos@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'jack.ramos',
  },
  {
    id: 'E02147',
    firstName: 'Riley',
    lastName: 'King',
    basicSalary: 16348000,
    birthDate: '2017/8/9',
    description: '',
    email: 'riley.king@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'riley.king',
  },
  {
    id: 'E02148',
    firstName: 'Naomi',
    lastName: 'Lee',
    basicSalary: 9113200,
    birthDate: '2019/2/17',
    description: '',
    email: 'naomi.lee@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'naomi.lee',
  },
  {
    id: 'E02149',
    firstName: 'Caleb',
    lastName: 'Jones',
    basicSalary: 12282500,
    birthDate: '2010/1/10',
    description: '',
    email: 'caleb.jones@example.com',
    group: 'Marketing',
    status: 'Tetap',
    userName: 'caleb.jones',
  },
  {
    id: 'E02150',
    firstName: 'Peyton',
    lastName: 'Alvarado',
    basicSalary: 7361200,
    birthDate: '2017/2/3',
    description: '',
    email: 'peyton.alvarado@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'peyton.alvarado',
  },
  {
    id: 'E02151',
    firstName: 'Luca',
    lastName: 'Liu',
    basicSalary: 7056100,
    birthDate: '2016/5/7',
    description: '',
    email: 'luca.liu@example.com',
    group: 'Sales',
    status: 'Magang',
    userName: 'luca.liu',
  },
  {
    id: 'E02152',
    firstName: 'Christian',
    lastName: 'Johnson',
    basicSalary: 6033100,
    birthDate: '2019/3/11',
    description: '',
    email: 'christian.johnson@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'christian.johnson',
  },
  {
    id: 'E02153',
    firstName: 'Kinsley',
    lastName: 'Gonzales',
    basicSalary: 4877200,
    birthDate: '2016/3/11',
    description: '',
    email: 'kinsley.gonzales@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'kinsley.gonzales',
  },
  {
    id: 'E02154',
    firstName: 'Hunter',
    lastName: 'Yoon',
    basicSalary: 9059900,
    birthDate: '2016/7/18',
    description: '',
    email: 'hunter.yoon@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'hunter.yoon',
  },
  {
    id: 'E02155',
    firstName: 'Elias',
    lastName: 'Dixon',
    basicSalary: 5564300,
    birthDate: '2013/6/22',
    description: '',
    email: 'elias.dixon@example.com',
    group: 'Human Resource',
    status: 'Magang',
    userName: 'elias.dixon',
  },
  {
    id: 'E02156',
    firstName: 'Owen',
    lastName: 'Guerrero',
    basicSalary: 9793800,
    birthDate: '2018/2/6',
    description: '',
    email: 'owen.guerrero@example.com',
    group: 'IT Suuport',
    status: 'Tetap',
    userName: 'owen.guerrero',
  },
  {
    id: 'E02157',
    firstName: 'Lucas',
    lastName: 'Lo',
    basicSalary: 4962700,
    birthDate: '2018/10/11',
    description: '',
    email: 'lucas.lo@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'lucas.lo',
  },
  {
    id: 'E02158',
    firstName: 'Hunter',
    lastName: 'Mitchell',
    basicSalary: 5813700,
    birthDate: '2012/3/19',
    description: '',
    email: 'hunter.mitchell@example.com',
    group: 'Marketing',
    status: 'Kontrak',
    userName: 'hunter.mitchell',
  },
  {
    id: 'E02159',
    firstName: 'Eliana',
    lastName: 'Bailey',
    basicSalary: 12058600,
    birthDate: '2011/7/22',
    description: '',
    email: 'eliana.bailey@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'eliana.bailey',
  },
  {
    id: 'E02160',
    firstName: 'Gabriella',
    lastName: 'Choi',
    basicSalary: 7292500,
    birthDate: '2015/7/25',
    description: '',
    email: 'gabriella.choi@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'gabriella.choi',
  },
  {
    id: 'E02161',
    firstName: 'Evelyn',
    lastName: 'Alvarado',
    basicSalary: 8354800,
    birthDate: '2020/10/12',
    description: '',
    email: 'evelyn.alvarado@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'evelyn.alvarado',
  },
  {
    id: 'E02162',
    firstName: 'Wyatt',
    lastName: 'Chan',
    basicSalary: 12822600,
    birthDate: '2010/10/1',
    description: '',
    email: 'wyatt.chan@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'wyatt.chan',
  },
  {
    id: 'E02163',
    firstName: 'Sarah',
    lastName: 'Johnson',
    basicSalary: 15065300,
    birthDate: '2020/9/3',
    description: '',
    email: 'sarah.johnson@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'sarah.johnson',
  },
  {
    id: 'E02164',
    firstName: 'Brooks',
    lastName: 'Evans',
    basicSalary: 8098900,
    birthDate: '2017/4/25',
    description: '',
    email: 'brooks.evans@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'brooks.evans',
  },
  {
    id: 'E02165',
    firstName: 'Isaiah',
    lastName: 'Dixon',
    basicSalary: 7490100,
    birthDate: '2010/4/19',
    description: '',
    email: 'isaiah.dixon@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'isaiah.dixon',
  },
  {
    id: 'E02166',
    firstName: 'Addison',
    lastName: 'Lo',
    basicSalary: 6871200,
    birthDate: '2012/4/1',
    description: '',
    email: 'addison.lo@example.com',
    group: 'IT Infrastructure',
    status: 'Kontrak',
    userName: 'addison.lo',
  },
  {
    id: 'E02167',
    firstName: 'Nolan',
    lastName: 'Howard',
    basicSalary: 8296300,
    birthDate: '2016/4/4',
    description: '',
    email: 'nolan.howard@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'nolan.howard',
  },
  {
    id: 'E02168',
    firstName: 'Paisley',
    lastName: 'Dominguez',
    basicSalary: 12320300,
    birthDate: '2014/2/13',
    description: '',
    email: 'paisley.dominguez@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'paisley.dominguez',
  },
  {
    id: 'E02169',
    firstName: 'Eliana',
    lastName: 'Ho',
    basicSalary: 19541600,
    birthDate: '2015/5/21',
    description: '',
    email: 'eliana.ho@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'eliana.ho',
  },
  {
    id: 'E02170',
    firstName: 'Charles',
    lastName: 'Miller',
    basicSalary: 15641800,
    birthDate: '2013/7/5',
    description: '',
    email: 'charles.miller@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'charles.miller',
  },
  {
    id: 'E02171',
    firstName: 'Mia',
    lastName: 'Jiang',
    basicSalary: 25589200,
    birthDate: '2017/7/17',
    description: '',
    email: 'mia.jiang@example.com',
    group: 'IT Suuport',
    status: 'Magang',
    userName: 'mia.jiang',
  },
  {
    id: 'E02172',
    firstName: 'Skylar',
    lastName: 'Parker',
    basicSalary: 9619500,
    birthDate: '2019/8/9',
    description: '',
    email: 'skylar.parker@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'skylar.parker',
  },
  {
    id: 'E02173',
    firstName: 'Zoey',
    lastName: 'Leung',
    basicSalary: 7763700,
    birthDate: '2017/1/6',
    description: '',
    email: 'zoey.leung@example.com',
    group: 'Sales',
    status: 'Kontrak',
    userName: 'zoey.leung',
  },
  {
    id: 'E02174',
    firstName: 'Austin',
    lastName: 'Moua',
    basicSalary: 7929400,
    birthDate: '2012/8/25',
    description: '',
    email: 'austin.moua@example.com',
    group: 'Human Resource',
    status: 'Kontrak',
    userName: 'austin.moua',
  },
  {
    id: 'E02175',
    firstName: 'Christopher',
    lastName: 'Robinson',
    basicSalary: 25428700,
    birthDate: '2018/4/24',
    description: '',
    email: 'christopher.robinson@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'christopher.robinson',
  },
  {
    id: 'E02176',
    firstName: 'Jayden',
    lastName: 'Zhang',
    basicSalary: 7051600,
    birthDate: '2013/4/14',
    description: '',
    email: 'jayden.zhang@example.com',
    group: 'IT Suuport',
    status: 'Kontrak',
    userName: 'jayden.zhang',
  },
  {
    id: 'E02177',
    firstName: 'Cora',
    lastName: 'Mejia',
    basicSalary: 9829600,
    birthDate: '2017/8/6',
    description: '',
    email: 'cora.mejia@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'cora.mejia',
  },
  {
    id: 'E02178',
    firstName: 'Julian',
    lastName: 'Harris',
    basicSalary: 9856500,
    birthDate: '2016/9/14',
    description: '',
    email: 'julian.harris@example.com',
    group: 'Human Resource',
    status: 'Tetap',
    userName: 'julian.harris',
  },
  {
    id: 'E02179',
    firstName: 'Anthony',
    lastName: 'Espinoza',
    basicSalary: 5914900,
    birthDate: '2011/9/5',
    description: '',
    email: 'anthony.espinoza@example.com',
    group: 'Finance',
    status: 'Magang',
    userName: 'anthony.espinoza',
  },
  {
    id: 'E02180',
    firstName: 'Aubrey',
    lastName: 'Ruiz',
    basicSalary: 7012600,
    birthDate: '2019/7/14',
    description: '',
    email: 'aubrey.ruiz@example.com',
    group: 'Customer Service',
    status: 'Magang',
    userName: 'aubrey.ruiz',
  },
  {
    id: 'E02181',
    firstName: 'Piper',
    lastName: 'Tang',
    basicSalary: 21678700,
    birthDate: '2014/2/21',
    description: '',
    email: 'piper.tang@example.com',
    group: 'IT Development',
    status: 'Tetap',
    userName: 'piper.tang',
  },
  {
    id: 'E02182',
    firstName: 'Colton',
    lastName: 'Delgado',
    basicSalary: 15651200,
    birthDate: '2014/6/3',
    description: '',
    email: 'colton.delgado@example.com',
    group: 'IT Suuport',
    status: 'Kontrak',
    userName: 'colton.delgado',
  },
  {
    id: 'E02183',
    firstName: 'Madeline',
    lastName: 'Chung',
    basicSalary: 4444400,
    birthDate: '2018/5/13',
    description: '',
    email: 'madeline.chung@example.com',
    group: 'Accounting',
    status: 'Kontrak',
    userName: 'madeline.chung',
  },
  {
    id: 'E02184',
    firstName: 'Ariana',
    lastName: 'Sharma',
    basicSalary: 25772500,
    birthDate: '2016/3/4',
    description: '',
    email: 'ariana.sharma@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'ariana.sharma',
  },
  {
    id: 'E02185',
    firstName: 'Julian',
    lastName: 'Marquez',
    basicSalary: 12240800,
    birthDate: '2015/3/24',
    description: '',
    email: 'julian.marquez@example.com',
    group: 'Customer Service',
    status: 'Tetap',
    userName: 'julian.marquez',
  },
  {
    id: 'E02186',
    firstName: 'Logan',
    lastName: 'Reyes',
    basicSalary: 7825100,
    birthDate: '2015/9/10',
    description: '',
    email: 'logan.reyes@example.com',
    group: 'IT Suuport',
    status: 'Tetap',
    userName: 'logan.reyes',
  },
  {
    id: 'E02187',
    firstName: 'Penelope',
    lastName: 'Mai',
    basicSalary: 25293800,
    birthDate: '2019/5/6',
    description: '',
    email: 'penelope.mai@example.com',
    group: 'Customer Service',
    status: 'Kontrak',
    userName: 'penelope.mai',
  },
  {
    id: 'E02188',
    firstName: 'Ryan',
    lastName: 'Reed',
    basicSalary: 9029600,
    birthDate: '2020/2/16',
    description: '',
    email: 'ryan.reed@example.com',
    group: 'Marketing',
    status: 'Magang',
    userName: 'ryan.reed',
  },
  {
    id: 'E02189',
    firstName: 'Grayson',
    lastName: 'Hwang',
    basicSalary: 9168900,
    birthDate: '2017/7/23',
    description: '',
    email: 'grayson.hwang@example.com',
    group: 'IT Development',
    status: 'Magang',
    userName: 'grayson.hwang',
  },
  {
    id: 'E02190',
    firstName: 'Ezra',
    lastName: 'Tan',
    basicSalary: 15802800,
    birthDate: '2012/1/11',
    description: '',
    email: 'ezra.tan@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'ezra.tan',
  },
  {
    id: 'E02191',
    firstName: 'David',
    lastName: 'Ha',
    basicSalary: 8975900,
    birthDate: '2016/5/3',
    description: '',
    email: 'david.ha@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'david.ha',
  },
  {
    id: 'E02192',
    firstName: 'Lillian',
    lastName: 'Vang',
    basicSalary: 7864000,
    birthDate: '2017/7/19',
    description: '',
    email: 'lillian.vang@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'lillian.vang',
  },
  {
    id: 'E02193',
    firstName: 'Sofia',
    lastName: 'Zhang',
    basicSalary: 5536800,
    birthDate: '2017/2/25',
    description: '',
    email: 'sofia.zhang@example.com',
    group: 'IT Infrastructure',
    status: 'Tetap',
    userName: 'sofia.zhang',
  },
  {
    id: 'E02194',
    firstName: 'Athena',
    lastName: 'Daniels',
    basicSalary: 7816400,
    birthDate: '2020/1/13',
    description: '',
    email: 'athena.daniels@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'athena.daniels',
  },
  {
    id: 'E02195',
    firstName: 'Jameson',
    lastName: 'Shin',
    basicSalary: 7601400,
    birthDate: '2014/4/1',
    description: '',
    email: 'jameson.shin@example.com',
    group: 'IT Development',
    status: 'Kontrak',
    userName: 'jameson.shin',
  },
  {
    id: 'E02196',
    firstName: 'Everly',
    lastName: 'Avila',
    basicSalary: 6140300,
    birthDate: '2018/3/25',
    description: '',
    email: 'everly.avila@example.com',
    group: 'Finance',
    status: 'Kontrak',
    userName: 'everly.avila',
  },
  {
    id: 'E02197',
    firstName: 'Liam',
    lastName: 'Nelson',
    basicSalary: 8072000,
    birthDate: '2019/1/25',
    description: '',
    email: 'liam.nelson@example.com',
    group: 'Finance',
    status: 'Tetap',
    userName: 'liam.nelson',
  },
  {
    id: 'E02198',
    firstName: 'Theodore',
    lastName: 'Lai',
    basicSalary: 9402600,
    birthDate: '2020/8/3',
    description: '',
    email: 'theodore.lai@example.com',
    group: 'Engineering',
    status: 'Kontrak',
    userName: 'theodore.lai',
  },
  {
    id: 'E02199',
    firstName: 'Caroline',
    lastName: 'Do',
    basicSalary: 5696300,
    birthDate: '2016/1/17',
    description: '',
    email: 'caroline.do@example.com',
    group: 'IT Infrastructure',
    status: 'Magang',
    userName: 'caroline.do',
  },
  {
    id: 'E02200',
    firstName: 'Josiah',
    lastName: 'Ramos',
    basicSalary: 11324600,
    birthDate: '2016/9/10',
    description: '',
    email: 'josiah.ramos@example.com',
    group: 'Sales',
    status: 'Tetap',
    userName: 'josiah.ramos',
  },
  {
    id: 'E02201',
    firstName: 'Colton',
    lastName: 'Alexander',
    basicSalary: 7641600,
    birthDate: '2017/1/20',
    description: '',
    email: 'colton.alexander@example.com',
    group: 'IT Suuport',
    status: 'Tetap',
    userName: 'colton.alexander',
  },
];

export const GroupListDummy = [
  {
    name: 'Finance',
    value: 'finance',
  },
];
